### ISSUE TITLE
[FE] basic claim info accordion section layout

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/Claim-for-Crown-Court-Defence#1108] opened 2016-03-01 15:17 UTC
<img width="908" alt="screen shot 2016-03-01 at 15 15 17" src="https://cloud.githubusercontent.com/assets/7016425/13431257/90b1879a-dfc0-11e5-8b16-2d789e180667.png">

**Comment by aliuk2012** [comment] 2016-03-01 18:03
Duplicate of #1099

**Closed as completed by aliuk2012** 2016-03-01 18:03 UTC
Labels: bug, frontend
